#!/bin/sh

# a package removal script for monkeysphere (borrowing from
# monkeysphere's debian/monkeysphere.postrm)

# Author: Daniel Kahn Gillmor <dkg@fifthhorseman.net>
# Copyright 2008

# FIXME: is /var/lib/monkeysphere the right place for this stuff on
# FreeBSD?
VARLIB="/var/monkeysphere"


case $2 in
POST-DEINSTALL)
# FIXME: This needs to be filled in!  Under what circumstances do we
# want to actually purge all of /var/monkeysphere?

# (note: FreeBSD does not seem to want the package-specific user to be
# purged at package removal)
	echo "Warning: If you will *NOT* use this package anymore, please remove the monkeysphere user manually."
	echo "         You may also want to remove the cached authentication data and keyrings in $VARLIB"
;;
esac
