#!/bin/sh
# monkeysphere-authentication cron.hourly script
#
# The monkeysphere scripts are written by:
# Jameson Rollins <jrollins@fifthhorseman.net>
# Jamie McClelland <jm@mayfirst.org>
# Daniel Kahn Gillmor <dkg@fifthhorseman.net>
# Micah Anderson <micah@riseup.net>
#
# They are Copyright 2008-2009, and are all released under the GPL, version 3
# or later.

# update all keys from the key servers
monkeysphere-authentication refresh-keys

# update all user authorized_keys files
monkeysphere-authentication update-users
