#!/usr/bin/env bash

# Tests to ensure that the monkeysphere is working

# Author: Daniel Kahn Gillmor <dkg@fifthhorseman.net>
# Date: 2008-09-13 13:40:15-0400

# these tests might be best run under fakeroot, particularly the
# "server-side" tests.  Using fakeroot, they should be able to be run
# as a non-privileged user.

# NOTE: these tests have *not* themselves been tested yet
# (2008-09-13).  Please exercise with caution!

# these tests assume a commonly-trusted "Admin's key", a fake key
# permanently stored in ./home/admin/.gnupg:
gpgadmin() {
    GNUPGHOME="$TESTDIR"/home/admin/.gnupg gpg "$@"
}

# cleanup:
cleanup() {
    # FIXME: stop the sshd process

    echo
    echo "### removing temp dir..."
    rm -rf "$TEMPDIR"

    # FIXME: how should we clear out the temporary $VARLIB?

    # FIXME: clear out ssh client config file and known hosts.
}

## setup trap
trap cleanup EXIT

## set up some variables to ensure that we're operating strictly in
## the tests, not system-wide:

export TESTDIR=$(pwd)

# make temp dir
TEMPDIR="$TESTDIR"/tmp
if [ -e "$TEMPDIR" ] ; then
    echo "tempdir '$TEMPDIR' already exists."
    exit 1
fi
mkdir "$TEMPDIR"

# Use the local copy of executables first, instead of system ones.
# This should help us test without installing.
export PATH="$TESTDIR"/../src:"$TESTDIR"/../src/keytrans:"$PATH"

export MONKEYSPHERE_SYSDATADIR="$TEMPDIR"
export MONKEYSPHERE_SYSCONFIGDIR="$TEMPDIR"
export MONKEYSPHERE_SYSSHAREDIR="$TESTDIR"/../src
export MONKEYSPHERE_MONKEYSPHERE_USER="$USER"
export MONKEYSPHERE_CHECK_KEYSERVER=false

SSHD_CONFIG="$TEMPDIR"/sshd_config
export SOCKET="$TEMPDIR"/ssh-socket


### SERVER TESTS

# create the temp gnupghome directories
mkdir -p -m 750 "$MONKEYSPHERE_SYSDATADIR"/gnupg-host
mkdir -p -m 700 "$MONKEYSPHERE_SYSDATADIR"/gnupg-authentication

# add the quick-random option to the gpg host config
echo "quick-random" >> "$MONKEYSPHERE_SYSCONFIGDIR"/gnupg-host/gpg.conf

# create a new host key
echo "### generating server key..."
echo | monkeysphere-server gen-key --length 1024 --expire 0 testhost

HOSTKEYID=$( monkeysphere-server show-key | tail -n1 | cut -f3 -d\  )

# certify it with the "Admin's Key".
# (this would normally be done via keyservers)
echo "### certifying server key..."
monkeysphere-server gpg-authentication-cmd "--armor --export $HOSTKEYID" | gpgadmin --import
gpgadmin --sign-key "$HOSTKEYID"

# FIXME: how can we test publish-key without flooding junk into the
# keyservers?

# indicate that the "Admin's" key is an identity certifier for the
# host

echo "### adding admin as certifier..."
monkeysphere-server add-identity-certifier "$TESTDIR"/home/admin/.gnupg/pubkey.gpg

# initialize base sshd_config
cp etc/ssh/sshd_config "$SSHD_CONFIG"
# write the sshd_config
cat <<EOF >> "$SSHD_CONFIG"
HostKey ${MONKEYSPHERE_SYSDATADIR}/ssh_host_rsa_key
AuthorizedKeysFile ${MONKEYSPHERE_SYSDATADIR}/authorized_keys/%u
EOF

# launch test sshd with the new host key.
echo "### starting sshd..."
socat EXEC:'/usr/sbin/sshd -f '"$SSHD_CONFIG"' -i -d -d -d -D -e' "UNIX-LISTEN:${SOCKET}" &


### TESTUSER TESTS

# copy testuser home directory into temp dir
cp -r "$TESTDIR"/home/testuser "$TEMPDIR"/

# generate an auth subkey for the test user
echo "### generating key for testuser..."
MONKEYSPHERE_GNUPGHOME="$TEMPDIR"/testuser/.gnupg \
    monkeysphere gen-subkey --expire 0

# add server key to testuser keychain
monkeysphere-server gpg-authentication-cmd "--armor --export $HOSTKEYID" | \
    GNUPGHOME="$TEMPDIR"/testuser/.gnupg gpg --import

# connect to test sshd, using monkeysphere to verify the identity
# before connection.
echo "### connecting to sshd socket..."
PROXY_COMMAND="monkeysphere-ssh-proxycommand --no-connect %h && socat STDIO UNIX:${SOCKET}"
ssh -oProxyCommand="$PROXY_COMMAND" testhost

# create a new client side key, certify it with the "CA", use it to
# log in.
## FIXME: implement!


### FINISH
read -p "press enter to cleanup tmp:"
