#!/bin/bash

printf "OK Pleased to meet you\n"

while read command rest; do
    case "${command,,}" in
        bye)
            exit 0
            ;;
        getpin)
            printf "D abc123\nOK\n"
            ;;
        *)
            printf >&2 "received %s %s\n" "$command" "$rest"
            printf "OK\n"
    esac
done
