#!/usr/bin/env bash

# Monkeysphere host add-hostname subcommand
#
# The monkeysphere scripts are written by:
# Jameson Rollins <jrollins@fifthhorseman.net>
# Jamie McClelland <jm@mayfirst.org>
# Daniel Kahn Gillmor <dkg@fifthhorseman.net>
#
# They are Copyright 2008, and are all released under the GPL, version 3
# or later.

# add hostname user ID to server key

local userID
local fingerprint
local tmpuidMatch
local line
local adduidCommand

if [ -z "$1" ] ; then
    failure "You must specify a hostname to add."
fi

userID="ssh://${1}"

fingerprint=$(fingerprint_server_key)

# match to only ultimately trusted user IDs
tmpuidMatch="u:$(echo $userID | gpg_escape)"

# find the index of the requsted user ID
# NOTE: this is based on circumstantial evidence that the order of
# this output is the appropriate index
if line=$(gpg_host --list-keys --with-colons --fixed-list-mode "0x${fingerprint}!" \
    | egrep '^(uid|uat):' | cut -f2,10 -d: | grep -n -x -F "$tmpuidMatch") ; then
    failure "Host userID '$userID' already exists."
fi

echo "The following user ID will be added to the host key:"
echo "  $userID"
read -p "Are you sure you would like to add this user ID? (y/N) " OK; OK=${OK:=N}
if [ ${OK/y/Y} != 'Y' ] ; then
    failure "User ID not added."
fi

# edit-key script command to add user ID
adduidCommand=$(cat <<EOF
adduid
$userID


save
EOF
)

# execute edit-key script
if echo "$adduidCommand" | \
    gpg_host --quiet --command-fd 0 --edit-key "0x${fingerprint}!" ; then

    # update the trustdb for the authentication keyring
    gpg_authentication "--check-trustdb"

    show_server_key

    echo
    echo "NOTE: User ID added to key, but key not published."
    echo "Run '$PGRM publish-key' to publish the new user ID."
else
    failure "Problem adding user ID."
fi
