#!/usr/bin/env bash

# simple socket-based proxy-command wrapper for testing monkeysphere.

# pass this thing the host, the port, and the socket.

monkeysphere-ssh-proxycommand --no-connect "$1" "$2" && \
socat STDIO UNIX:"$3"
