#!/bin/sh -e

# build a patched version of GnuTLS version 2.4.x, including the
# ability to parse and accept the GNU S2K extension known as
# "gnu-dummy" (which doesn't have any secret key data at all)

# Note: you probably want 

# Author: Daniel Kahn Gillmor <dkg@fifthhorseman.net>
# Date: 2008-08-22 00:11:05-0400

# Note: please run this from the current directory, so it can find and
# transfer the patch it needs.

workingdir=$(mktemp -d)

(cd "$workingdir" && apt-get source libgnutls26)

cp ./*.diff "$workingdir/gnutls26-2.4".*/debian/patches/

(cd "$workingdir/gnutls26-2.4".* && \
    dch --local .s2kext1 --distribution experimental 'added patch to handle GNU extensions to S2K' && \
    debuild -uc -us -sa)

echo now you should:
echo reprepro -C gnutls include experimental "$workingdir/"*.changes
