.\"  -*- nroff -*-
.Dd $Mdocdate: January 25, 2009 $
.Dt PEM2OPENPGP 1
.Os
.Sh NAME
pem2openpgp
.Nd translate PEM encoded keys to OpenPGP keys
.Sh SYNOPSIS
.Nm pem2openpgp $USERID < mykey.pem 
.Pp
.Nm ??? gpg --export $KEYID | openpgp2ssh $KEYID
.Pp
.Nm ????gpg --export-secret-key $KEYID | openpgp2ssh $KEYID
.Sh DESCRIPTION
.Nm
WRITE ME!!!
.Sh AUTHOR
.Nm
and this man page were written by Daniel Kahn Gillmor
<dkg@fifthhorseman.net>.
.Sh BUGS
.Sh SEE ALSO
.Xr openpgp2ssh 1,
.Xr monkeysphere 1 ,
.Xr monkeysphere 7 ,
.Xr ssh 1 ,
.Xr monkeysphere-server 8
