#!/bin/bash

# monkeysphere: MonkeySphere client tool
#
# The monkeysphere scripts are written by:
# Jameson Rollins <jrollins@fifthhorseman.net>
#
# They are Copyright 2008, and are all released under the GPL, version 3
# or later.

########################################################################
PGRM=$(basename $0)

SHARE=${MONKEYSPHERE_SHARE:-"/usr/share/monkeysphere"}
export SHARE
. "${SHARE}/common" || exit 1

# date in UTF format if needed
DATE=$(date -u '+%FT%T')

# unset some environment variables that could screw things up
unset GREP_OPTIONS

# default return code
RETURN=0

# set the file creation mask to be only owner rw
umask 077

########################################################################
# FUNCTIONS
########################################################################

usage() {
cat <<EOF
usage: $PGRM <subcommand> [options] [args]
MonkeySphere client tool.

subcommands:
  update-known_hosts (k) [HOST]...  update known_hosts file
  update-authorized_keys (a)        update authorized_keys file
  gen-subkey (g) KEYID              generate an 'a' capable subkey
    -l|--length BITS                  key length in bits (2048)
    -e|--expire EXPIRE                date to expire
  help (h,?)                        this help

EOF
}

# generate a subkey with the 'a' usage flags set
# FIXME: this needs some tweaking to clean it up
gen_subkey(){
    local keyID
    local gpgOut
    local userID

    keyID="$1"

    gpgOut=$(gpg --quiet --fixed-list-mode --list-keys --with-colons \
	"$keyID" 2> /dev/null)

    # fail if there only "tru" lines are output from gpg, which
    # indicates the key was not found.
    if [ -z "$(echo "$gpgOut" | grep -v '^tru:')" ] ; then
	failure "Key ID '$keyID' not found."
    fi

    # fail if multiple pub lines are returned, which means the id given
    # is not unique
    if [ $(echo "$gpgOut" | grep '^pub:' | wc -l) -gt '1' ] ; then
	failure "Key ID '$keyID' is not unique."
    fi

    # prompt if an authentication subkey already exists
    if echo "$gpgOut" | egrep "^(pub|sub):" | cut -d: -f 12 | grep -q a ; then
	echo "An authentication subkey already exists for key '$keyID'."
	read -p "Are you sure you would like to generate another one? (y/N) " OK; OK=${OK:N}
	if [ "${OK/y/Y}" != 'Y' ] ; then
	    failure "aborting."
	fi
    fi

    # set subkey defaults
    KEY_TYPE="RSA"
    KEY_LENGTH=${KEY_LENGTH:-}
    KEY_USAGE="auth"
    # prompt about key expiration if not specified
    if [ -z "$KEY_EXPIRE" ] ; then
	cat <<EOF
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
EOF
	while [ -z "$KEY_EXPIRE" ] ; do
	    read -p "Key is valid for? (0) " KEY_EXPIRE
	    if ! test_gpg_expire ${KEY_EXPIRE:=0} ; then
		echo "invalid value"
		unset KEY_EXPIRE
	    fi
	done
    elif ! test_gpg_expire "$KEY_EXPIRE" ; then
	failure "invalid key expiration value '$KEY_EXPIRE'."
    fi

    # generate the list of commands that will be passed to edit-key
    editCommands=$(cat <<EOF
addkey
7
S
E
A
Q
$KEY_LENGTH
$KEY_EXPIRE
save
EOF
)

    log "generating subkey..."
    echo "$editCommands" | gpg --expert --command-fd 0 --edit-key "$keyID"
    log "done."
}

########################################################################
# MAIN
########################################################################

# unset variables that should be defined only in config file
unset KEYSERVER
unset CHECK_KEYSERVER
unset KNOWN_HOSTS
unset HASH_KNOWN_HOSTS
unset AUTHORIZED_KEYS

# load global config
[ -r "${ETC}/monkeysphere.conf" ] && . "${ETC}/monkeysphere.conf"

# set monkeysphere home directory
MONKEYSPHERE_HOME=${MONKEYSPHERE_HOME:="${HOME}/.config/monkeysphere"}
mkdir -p -m 0700 "$MONKEYSPHERE_HOME"

# load local config
[ -e ${MONKEYSPHERE_CONFIG:="${MONKEYSPHERE_HOME}/monkeysphere.conf"} ] && . "$MONKEYSPHERE_CONFIG"

# set empty config variables with ones from the environment, or from
# config file, or with defaults
GNUPGHOME=${MONKEYSPHERE_GNUPGHOME:=${GNUPGHOME:="${HOME}/.gnupg"}}
KEYSERVER=${MONKEYSPHERE_KEYSERVER:=${KEYSERVER:="subkeys.pgp.net"}}
CHECK_KEYSERVER=${MONKEYSPHERE_CHECK_KEYSERVER:=${CHECK_KEYSERVER:="true"}}
KNOWN_HOSTS=${MONKEYSPHERE_KNOWN_HOSTS:=${KNOWN_HOSTS:="${HOME}/.ssh/known_hosts"}}
HASH_KNOWN_HOSTS=${MONKEYSPHERE_HASH_KNOWN_HOSTS:=${HASH_KNOWN_HOSTS:="true"}}
AUTHORIZED_KEYS=${MONKEYSPHERE_AUTHORIZED_KEYS:=${AUTHORIZED_KEYS:="${HOME}/.ssh/authorized_keys"}}

# other variables not in config file
AUTHORIZED_USER_IDS=${MONKEYSPHERE_AUTHORIZED_USER_IDS:="${MONKEYSPHERE_HOME}/authorized_user_ids"}
REQUIRED_HOST_KEY_CAPABILITY=${MONKEYSPHERE_REQUIRED_HOST_KEY_CAPABILITY:="a"}
REQUIRED_USER_KEY_CAPABILITY=${MONKEYSPHERE_REQUIRED_USER_KEY_CAPABILITY:="a"}

# export GNUPGHOME and make sure gpg home exists with proper
# permissions
export GNUPGHOME
mkdir -p -m 0700 "$GNUPGHOME"

# get subcommand
COMMAND="$1"
[ "$COMMAND" ] || failure "Type '$PGRM help' for usage."
shift

# unset option variables
unset KEY_LENGTH
unset KEY_EXPIRE

# get options for key generation and add-certifier functions
TEMP=$(getopt -o l:e: -l length:,expire: -n "$PGRM" -- "$@")

if [ $? != 0 ] ; then
    usage
    exit 1
fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
	-l|--length)
	    KEY_LENGTH="$2"
	    shift 2
	    ;;
	-e|--expire)
	    KEY_EXPIRE="$2"
	    shift 2
	    ;;
	--)
	    shift
	    ;;
        *)
            break
            ;;
    esac
done

case $COMMAND in
    'update-known_hosts'|'update-known-hosts'|'k')
	MODE='known_hosts'

	if ! check_key_file_permissions "$USER" "$KNOWN_HOSTS" ; then
	    failure "Improper permissions on known_hosts file."
	fi

        # if hosts are specified on the command line, process just
        # those hosts
	if [ "$1" ] ; then
	    update_known_hosts "$@"
	    RETURN="$?"

        # otherwise, if no hosts are specified, process every host
        # in the user's known_hosts file
	else
	    if [ ! -s "$KNOWN_HOSTS" ] ; then
		failure "known_hosts file '$KNOWN_HOSTS' is empty or does not exist."
	    fi

	    process_known_hosts
	    RETURN="$?"
	fi
	;;

    'update-authorized_keys'|'update-authorized-keys'|'a')
	MODE='authorized_keys'

        # fail if the authorized_user_ids file is empty
	if [ ! -s "$AUTHORIZED_USER_IDS" ] ; then
	    failure "authorized_user_ids file '$AUTHORIZED_USER_IDS' is empty or does not exist."
	fi

	if ! check_key_file_permissions "$USER" "$AUTHORIZED_USER_IDS" ; then
	    failure "Improper permissions on authorized_user_ids file."
	fi

	# process authorized_user_ids file
	process_authorized_user_ids "$AUTHORIZED_USER_IDS"
	RETURN="$?"
	;;

    'gen-subkey'|'g')
	keyID="$1"
	if [ -z "$keyID" ] ; then
	    failure "You must specify the key ID of your primary key."
	fi
	gen_subkey "$keyID"
	;;

    'help'|'h'|'?')
        usage
        ;;

    *)
        failure "Unknown command: '$COMMAND'
Type '$PGRM help' for usage."
        ;;
esac

exit "$RETURN"
